### PR TITLE
Update CACE datasheet and template

### PR DESCRIPTION
**Pull request by mole99**
With these changes the transient simulation runs again and LVS is clean. There are however DRC issues with KLayout.

### CODE REVIEW

**Comment by areda0** [comment]
I've done similar edits on my side on the same files and I confirm that the block passes the main checks except for "klayout_drc_feol" and "klayout_drc_full". 
there was also a pin left open "en" pin. I think it should connect to a dc supply CACE{en} and assigned the value "dvdd" in the default conditions. could it be fixed in the same push?

**Comment by mole99** [comment]
Thanks, that's what xschem was complaining about! I added the `en` condition which is multiplied by `dvdd`.

@RTimothyEdwards Could you let me know when Ahmed is already working on an IP so we don't do duplicate work?

**Comment by RTimothyEdwards** [comment]
@mole99 :  Let's start a spreadsheet on Google Docs so that we can all coordinate work on the set of IP blocks.

**Review by RTimothyEdwards — APPROVED** [review]
I assume this is all good.  My original file was a quick spin with some guess-work.

**Comment by mole99** [comment]
Alright, gonna merge this!

**Pull request merged**
